nextcloud:
  nextcloud:
    host: nextcloud.local

  existingSecret:
    enabled: True
    secretName: nextcloud-admin-secret
    usernameKey: username
    passowrdKey: password

  internalDatabase:
    enabled: True

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi

  service:
    type: LoadBalancer
    port: 8080
